name: 'SVG Color Replace'
description: 'Replace colors in SVG files with CSS variables from a JSON file token set'

inputs:
  svg-folder-path:
    description: 'The path to the folder containing the SVG files to process'
    required: true
  token-set-input-path:
    description: 'The path to the JSON file containing the token set'
    required: true
  dry-run:
    description: 'If true, the action will not write any files, only log the changes that would be made'
    required: false
  token-set-key:
    description: 'The key in the token set to use for the color replacement (e.g. "color.primary")'
    required: false
  prefer-deep-key:
    description: 'If true, the action will prefer a deep key in the token set (e.g. "color.primary.500") over a shallow key (e.g. "color.primary")'
    required: false
  css-map-output-path:
    description: 'The path to a JSON file to write the CSS variable map to'
    required: false
  file-extensions:
    description: 'The file extensions to process (e.g. ".svg, .tsx")'
    required: false
  inject-into-html:
    description: 'If true, the action will inject the CSS variables into the head of the HTML file'
    required: false
  html-path:
    description: 'The path to the HTML file to inject the CSS variables into'
    required: false
  css-output-path:
    description: 'The path to the CSS file to write the CSS variables to'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
