#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm run build:action
git restore --staged .
git add dist-action

if [[ $(git diff --cached --name-only | grep dist-action) ]]; then
  echo "dist-action folder is in git changes"
  git commit -m "🤖 Auto build update"
  exit 0
fi
