name: Create release

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/**.md'
      - '**/**.yml'
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Git tag
        if: github.ref == 'refs/heads/main'
        id: create-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git tag -a v$VERSION -m "Release v$VERSION"
          git push origin v$VERSION
          echo "::set-output name=tag::v$VERSION"

      - name: Create release
        uses: nbotond20/create-release@v1.2.3
        with:
          use-sem-ver: true
          tag: ${{ steps.create-tag.outputs.tag }}
